# PetPlugin Configuration
# Version: 1.0.0
# Author: YourServer

# Database settings
database:
  type: "SQLITE" # Options: SQLITE, MYSQL
  mysql:
    host: "localhost"
    port: 3306
    database: "pets"
    username: "root"
    password: ""

# General settings
settings:
  # Maximum pets per player (without bonuses)
  max-pets-default: 1

  # Pet follow distance
  follow-distance: 5.0

  # Pet teleport distance (if too far)
  teleport-distance: 10.0

  # Enable pet particles
  enable-particles: true

  # Enable pet sounds
  enable-sounds: true

  # Experience per mob kill
  exp-per-kill: 1.0

  # Experience formula multiplier
  exp-multiplier: 1.0

# Pet effect settings
head-database:
  # Enable integration with the HeadDatabase plugin. When disabled the plugin will use built-in base64 textures.
  enabled: true
  # Configure the HeadDatabase ID for each pet (example: "12345" or "MHF_Cow"). Leave empty to use the fallback texture.
  ids:
    COW: "115920"
    PIG: "106988"
    SHEEP: "106996"
    CHICKEN: "91925"
    DONKEY: "60046"
    SNOW_GOLEM: "109991"
    IRON_GOLEM: "91387"
    SQUID: "106953"
    TURTLE: "113122"
    LLAMA: "63388"
    ENDERMAN: "106947"
    WITCH: "57785"
    HUSK: "41306"
    MOOSHROOM: "114668"
    FROG: "118155"
    WOLF: "101519"
    BEE: "121380"
    WANDERING_TRADER: "65745"
    PANDA: "102148"
    ZOMBIE: "121331"
    SKELETON: "105478"
    SPIDER: "106952"
    CREEPER: "108631"
    SLIME: "118663"
    PHANTOM: "120109"
    GLOW_SQUID: "106975"
    GUARDIAN: "118998"
    SNIFFER: "89419"
    WITHER_SKELETON: "91413"
    ENDER_DRAGON: "114375"
    WARDEN: "81758"
    WITHER: "81665"
    GIANT: "121331"

effects:
  # Effect tick rate (in ticks, 20 = 1 second)
  tick-rate: 20

  # Effect values (easy to modify)
  cow:
    bonus-health: 4.0

  pig:
    money-chance: 5.0 # Percent
    money-min: 1
    money-max: 10

  sheep:
    heal-amount: 2.0
    heal-cooldown: 20 # Seconds

  chicken:
    luck-level: 1

  snow-golem:
    slow-radius: 5.0
    slow-duration: 3 # Seconds

  iron-golem:
    damage-multiplier: 2.0
    cooldown: 15 # Seconds

  squid:
    chest-chance-bonus: 15.0 # Percent

  turtle:
    damage-reduction: 10.0 # Percent

  llama:
    mob-damage-bonus: 15.0 # Percent

  enderman:
    free-tp-chance: 10.0 # Percent

  witch:
    potion-duration-bonus: 25.0 # Percent

  husk:
    mobsphere-chance-bonus: 12.0 # Percent

  mooshroom:
    farm-speed-bonus: 20.0 # Percent

  frog:
    honey-speed-bonus: 15.0 # Percent

  wolf:
    pvp-damage-bonus: 20.0 # Percent
    lifesteal: 15.0 # Percent (special effect)

  bee:
    honey-quality-bonus: 25.0 # Percent
    rare-honey-chance: 15.0 # Percent

  wandering-trader:
    craft-cost-reduction: 15.0 # Percent
    refund-chance: 10.0 # Percent (special effect)

  panda:
    farm-yield-bonus: 30.0 # Percent

  # Dungeon pets damage bonus
  dungeon-pets:
    damage-bonus: 20.0 # Percent

  phantom:
    treasure-chance-bonus: 20.0 # Percent

  glow-squid:
    rare-ore-chance-bonus: 18.0 # Percent

  # Mythic pets
  guardian:
    all-fishing-bonus: 30.0 # Percent

  sniffer:
    all-mining-bonus: 30.0 # Percent

  wither-skeleton:
    special-material-chance: 40.0 # Percent

  wither:
    boss-damage-bonus: 35.0 # Percent

  giant:
    mythic-item-chance-bonus: 50.0 # Percent

# Feeding settings
feeding:
  # Andermant item settings
  andermant-item:
    material: "SMALL_AMETHYST_BUD"
    name: "&5&lAndermant"
    lore:
      - "&o&7Premium currency"

  # Feed amounts required (base * (level/5))
  base-feed-amount: 100

  # Levels that require feeding
  feed-levels: [4, 9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84, 89, 94, 99]

# Level milestones
milestones:
  # Bonus multipliers at milestones
  level-25-bonus: 0.25
  level-50-bonus: 0.35
  level-75-bonus: 0.45
  level-100-bonus: 0.60

# Boss detection configuration for Wither pet
bosses:
  # Substrings that should match boss display names (legacy support)
  custom-names:
    - "SkeletalKnight"
    - "SkeletonKing"
    - "AngrySludge"
    - "StormKing"
    - "NetherLord"
  # MythicMob internal names flagged as bosses with their xp-per-mob values
  mythic-mobs:
    grimmag_inf:
      xp-per-mob: 60000
    grimmag_hell:
      xp-per-mob: 180000
    grimmag_blood:
      xp-per-mob: 600000
    arachna_scourge_of_duria_inf:
      xp-per-mob: 65000
    arachna_scourge_of_duria_hell:
      xp-per-mob: 190000
    arachna_scourge_of_duria_blood:
      xp-per-mob: 650000
    undead_parallel_world_king_heredur_inf:
      xp-per-mob: 70000
    undead_parallel_world_king_heredur_hell:
      xp-per-mob: 200000
    undead_parallel_world_king_heredur_blood:
      xp-per-mob: 700000
    bearach_champion_of_wilds_inf:
      xp-per-mob: 75000
    bearach_champion_of_wilds_hell:
      xp-per-mob: 210000
    bearach_champion_of_wilds_blood:
      xp-per-mob: 750000
    khalys_leader_of_cultists_inf:
      xp-per-mob: 80000
    khalys_leader_of_cultists_hell:
      xp-per-mob: 220000
    khalys_leader_of_cultists_blood:
      xp-per-mob: 800000
    skeledragon_phase1_inf:
      xp-per-mob: 29000
    skeledragon_phase2_inf:
      xp-per-mob: 29000
    mortis_phase3_inf:
      xp-per-mob: 29000
    skeledragon_phase1_hell:
      xp-per-mob: 77000
    skeledragon_phase2_hell:
      xp-per-mob: 77000
    mortis_phase3_hell:
      xp-per-mob: 77000
    skeledragon_phase1_blood:
      xp-per-mob: 280000
    skeledragon_phase2_blood:
      xp-per-mob: 280000
    mortis_phase3_blood:
      xp-per-mob: 280000
    herald_of_anderworld_inf:
      xp-per-mob: 90000
    herald_of_anderworld_hell:
      xp-per-mob: 240000
    herald_of_anderworld_blood:
      xp-per-mob: 880000
    sigrismarr_priest_of_fjalnir_inf:
      xp-per-mob: 95000
    sigrismarr_priest_of_fjalnir_hell:
      xp-per-mob: 250000
    sigrismarr_priest_of_fjalnir_blood:
      xp-per-mob: 920000
    medusa_inf:
      xp-per-mob: 100000
    medusa_hell:
      xp-per-mob: 260000
    medusa_blood:
      xp-per-mob: 960000
    parallel_world_gorga_inf:
      xp-per-mob: 110000
    parallel_world_gorga_hell:
      xp-per-mob: 280000
    parallel_world_gorga_blood:
      xp-per-mob: 1000000
    umbraxis_shadowlord:
      xp-per-mob: 120000
    poseidon_sea_lord:
      xp-per-mob: 130000
    zeus_king_of_gods:
      xp-per-mob: 360000
    daedalus_master_architect:
      xp-per-mob: 1200000
    hades_lord_of_underworld:
      xp-per-mob: 2000000

# Integration settings
integrations:
  # Enable/disable integrations
  vaults: true
  fishing-plugin: true
  dungeon-plugin: true
  alchemy-plugin: true
  mine-plugin: true
  farming-plugin: true
  beekeeper-plugin: true
  crafting-plugin: true
  mythicmobs: true

  # Integration placeholders (for PlaceholderAPI)
  placeholder-prefix: "pet_"

# Messages
messages:
  prefix: "&8[&6Pets&8] &7"

  no-permission: "&cYou don't have permission to do this!"
  pet-spawned: "&aYour %pet% has been summoned!"
  pet-despawned: "&cYour %pet% has been dismissed!"
  pet-level-up: "&a&lLEVEL UP! &7Your %pet% is now level &e%level%&7!"
  pet-max-level: "&6Your %pet% has reached maximum level!"
  pet-needs-feeding: "&cYour pet needs feeding to level up! Required: &5%amount%x Andermant"
  pet-fed: "&aYour pet has been fed and can now level up!"
  pet-limit-reached: "&cYou have reached your maximum pet limit!"
  pet-already-owned: "&cYou already own this type of pet!"
  pet-deleted: "&cYour %pet% has been released!"

  # GUI messages
  gui-title-main: "&8Pet Management"
  gui-title-pet: "&8Pet: %pet%"
  gui-activate: "&aClick to activate"
  gui-deactivate: "&cClick to deactivate"
  gui-feed: "&5Click to feed"
  gui-delete: "&c&lShift-Click to release"

# Sound effects
sounds:
  pet-spawn: "ENTITY_EXPERIENCE_ORB_PICKUP"
  pet-despawn: "ENTITY_ITEM_BREAK"
  pet-levelup: "UI_TOAST_CHALLENGE_COMPLETE"
  pet-feed: "ENTITY_GENERIC_EAT"
  menu-open: "UI_BUTTON_CLICK"
  menu-click: "UI_BUTTON_CLICK"

# Particle effects
particles:
  pet-spawn: "VILLAGER_HAPPY"
  pet-idle: "SPELL"
  pet-levelup: "TOTEM"
  pet-special: "END_ROD"

# Pet drop system configuration
pet-drops:
  # Global settings
  enabled: true
  testing: false # Set to true for 50% drop chance and equal rarity chances

  # Base drop chance (percentage)
  base-drop-chance: 0.1

  # Drop chance for each rarity when testing mode is enabled (50% total)
  testing-drop-chance: 50.0
  testing-equal-rarity: true

  # Drop chances for each rarity (when NOT in testing mode)
  drop-chances:
    magic: 40.0      # Block of Lapis
    extraordinary: 30.0  # Block of Amethyst
    legendary: 20.0  # Block of Diamond
    unique: 8.0      # Block of Emerald
    mythic: 2.0      # Block of Redstone

  # Block materials for each rarity
  drop-blocks:
    magic: "LAPIS_BLOCK"
    extraordinary: "AMETHYST_BLOCK"
    legendary: "DIAMOND_BLOCK"
    unique: "EMERALD_BLOCK"
    mythic: "REDSTONE_BLOCK"

  # Block display names
  block-names:
    magic: "&9&lMagic Pet Block"
    extraordinary: "&5&lExtraordinary Pet Block"
    legendary: "&6&lLegendary Pet Block"
    unique: "&e&lUnique Pet Block"
    mythic: "&c&lMythic Pet Block"

  # Block lore
  block-lore:
    - "&7Right click to obtain a random pet!"
    - "&7Rarity: %rarity%"

  # Messages
  drop-messages:
    pet-dropped: "&8[&6DROP&8] &7%player% &7has dropped a %rarity% &7pet!"
    pet-obtained: "&aYou obtained a %rarity% %pet%!"

# Debug mode
debug: false
